### ISSUE TITLE
Didn't compile with ffmpeg 4.0

### ISSUE THREAD

**Issue by ocochard** [MrKepzie/openfx-io#36]
Hi, openfx-io didn't compile with ffmpeg 4.0:

```
In file included from ../FFmpeg/ReadFFmpeg.cpp:45:
../FFmpeg/FFmpegFile.h:268:53: error: use of undeclared identifier 'CODEC_CAP_DELAY'
            return ( ( (_videoCodec->capabilities & CODEC_CAP_DELAY) ? _codecContext->delay : 0 )
                                                    ^
../FFmpeg/ReadFFmpeg.cpp:626:30: warning: 'av_iformat_next' is deprecated [-Wdeprecated-declarations]
    AVInputFormat* iFormat = av_iformat_next(NULL);
                             ^
```

**Comment by devernay** [comment]
The currently maintained version at https://github.com/NatronGitHub/openfx-io/ does.
